// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5577.GearsBot.subsystems;

import org.usfirst.frc5577.GearsBot.Robot;
import org.usfirst.frc5577.GearsBot.RobotMap;
import org.usfirst.frc5577.GearsBot.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

/**
 *
 */
public class DriveTrain extends Subsystem {
    SpeedController rightMotor = RobotMap.driveTrainRightMotor;
    SpeedController leftMotor = RobotMap.driveTrainLeftMotor;
    DifferentialDrive robotDrive = RobotMap.driveTrainRobotDrive;

    double driveTrainSpeed = 1.0;

    public DriveTrain() {

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        setDefaultCommand(new DriveWithJoysticks());
    }

    public void driveTrainForwardWithDistance(double distance) {
        robotDrive.arcadeDrive(0.25, 1);
    }

    public void driveTrainFoward(double speed) {
        robotDrive.arcadeDrive(speed, 0);
    }

    public void driveTrainBackward(double speed) {
        robotDrive.arcadeDrive(-speed, 0);
    }

    public void turn(double rotateValue) {
        robotDrive.setSafetyEnabled(true);
        robotDrive.arcadeDrive(0.1, -rotateValue, true);
    }

    public void takeJoystickInputs(Joystick xBoxController) {
        robotDrive.setSafetyEnabled(true);

        /*
         * The two options for driving are tank drive and arcade mode. To choose tank
         * you comment arcade out (i.e. //robotDrive.arcadeDrive...) To choose arcade
         * you comment tank out (i.e. //robotDrive.tankDrive...)
         * 
         */
        // robotDrive.arcadeDrive(xBoxCont);

        double speedValue = xBoxController.getRawAxis(Robot.oi.LEFT_AXIS_Y);
        double rotateValue = -xBoxController.getRawAxis(Robot.oi.LEFT_AXIS_X);
        double maxRotateSpeed = 0.5;
        double minRotateSpeed = -0.5;

        // if (rotateValue > maxRotateSpeed) {
        // rotateValue = maxRotateSpeed;
        // }
        // if (rotateValue < minRotateSpeed) {
        // rotateValue = minRotateSpeed;
        // }

        robotDrive.arcadeDrive(speedValue * driveTrainSpeed, rotateValue * driveTrainSpeed, true);

        // "Smoother Step" idea below
        // robotDrive.arcadeDrive(Math.signum(speedValue) * smootherstep(0, 1,
        // Math.abs(speedValue)) * driveTrainSpeed,
        // Math.signum(rotateValue) * smootherstep(0, 1, Math.abs(rotateValue)) *
        // driveTrainSpeed, false);
    }

    double smootherstep(double edge0, double edge1, double x) {
        // Scale, and clamp x to 0..1 range
        x = clamp((x - edge0) / (edge1 - edge0), 0.0, 1.0);
        // Evaluate polynomial
        return x * x * x * (x * (x * 6 - 15) + 10);
    }

    double clamp(double x, double lowerlimit, double upperlimit) {
        if (x < lowerlimit)
            x = lowerlimit;
        if (x > upperlimit)
            x = upperlimit;
        return x;
    }

    public void stop() {
        robotDrive.arcadeDrive(0, 0);
    }

}
